-- Kura Space — Supabase schema, security policies, storage and functions
-- Run this entire file once in Supabase Dashboard → SQL Editor.
-- It is designed to be safe to run again.

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  service_type text not null check (service_type in ('virtual', 'in_person')),
  booking_date date not null,
  booking_time time without time zone not null,
  name text not null,
  email text not null,
  phone text not null default '',
  notes text not null default '',
  status text not null default 'confirmed'
    check (status in ('confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.availability_slots (
  id bigint generated by default as identity primary key,
  service_type text not null check (service_type in ('virtual', 'in_person')),
  slot_date date not null,
  slot_time time without time zone not null,
  is_booked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (service_type, slot_date, slot_time)
);

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  service_type text not null default 'in_person'
    check (service_type in ('virtual', 'in_person')),
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  presentation_type text not null default 'before_after'
    check (presentation_type in ('before_after', 'after_only')),
  location text not null default '',
  project_date text not null default '',
  summary text not null default '',
  goals text not null default '',
  what_changed text not null default '',
  client_items text not null default '',
  purchased_items text not null default '',
  constraints_text text not null default '',
  service_format text not null default '',
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  image_path text not null,
  storage_path text,
  label text not null default 'gallery'
    check (label in ('before', 'after', 'gallery')),
  sort_order integer not null default 0
);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  quote text not null,
  author text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists bookings_date_idx
  on public.bookings (booking_date, booking_time);

create index if not exists availability_slots_lookup_idx
  on public.availability_slots (service_type, slot_date, is_booked);

create index if not exists project_images_project_idx
  on public.project_images (project_id, label, sort_order);

-- ---------------------------------------------------------------------------
-- Admin helper
-- ---------------------------------------------------------------------------

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Transaction-safe public/admin functions
-- ---------------------------------------------------------------------------

create or replace function public.create_booking(
  p_service_type text,
  p_slot_date date,
  p_slot_time time without time zone,
  p_name text,
  p_email text,
  p_phone text default '',
  p_notes text default ''
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_slot_id bigint;
  v_booking_id bigint;
begin
  if p_service_type not in ('virtual', 'in_person') then
    raise exception 'Invalid service type.';
  end if;

  if p_slot_date < current_date then
    raise exception 'The selected date is in the past.';
  end if;

  if length(trim(coalesce(p_name, ''))) < 2 then
    raise exception 'Please enter your full name.';
  end if;

  if coalesce(p_email, '') !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Please enter a valid email address.';
  end if;

  if p_service_type = 'in_person'
     and coalesce(
       (select value from public.settings where key = 'in_person_status'),
       'fully_booked'
     ) <> 'available' then
    raise exception 'In-person appointments are not currently available.';
  end if;

  select id
  into v_slot_id
  from public.availability_slots
  where service_type = p_service_type
    and slot_date = p_slot_date
    and slot_time = p_slot_time
    and is_booked = false
  for update;

  if v_slot_id is null then
    raise exception 'That time slot is no longer available.';
  end if;

  update public.availability_slots
  set is_booked = true
  where id = v_slot_id;

  insert into public.bookings (
    service_type, booking_date, booking_time,
    name, email, phone, notes, status
  )
  values (
    p_service_type, p_slot_date, p_slot_time,
    trim(p_name), lower(trim(p_email)),
    trim(coalesce(p_phone, '')),
    trim(coalesce(p_notes, '')),
    'confirmed'
  )
  returning id into v_booking_id;

  return v_booking_id;
end;
$$;

revoke all on function public.create_booking(
  text, date, time without time zone, text, text, text, text
) from public;
grant execute on function public.create_booking(
  text, date, time without time zone, text, text, text, text
) to anon, authenticated;

create or replace function public.join_waitlist(
  p_name text,
  p_email text,
  p_phone text default '',
  p_service_type text default 'in_person'
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
begin
  if p_service_type not in ('virtual', 'in_person') then
    raise exception 'Invalid service type.';
  end if;

  if length(trim(coalesce(p_name, ''))) < 2 then
    raise exception 'Please enter your full name.';
  end if;

  if coalesce(p_email, '') !~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' then
    raise exception 'Please enter a valid email address.';
  end if;

  insert into public.waitlist (name, email, phone, service_type)
  values (
    trim(p_name),
    lower(trim(p_email)),
    trim(coalesce(p_phone, '')),
    p_service_type
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.join_waitlist(text, text, text, text) from public;
grant execute on function public.join_waitlist(text, text, text, text)
  to anon, authenticated;

create or replace function public.set_booking_status(
  p_booking_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_booking public.bookings%rowtype;
  v_slot public.availability_slots%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Unauthorized.';
  end if;

  if p_status not in ('confirmed', 'cancelled') then
    raise exception 'Invalid booking status.';
  end if;

  select *
  into v_booking
  from public.bookings
  where id = p_booking_id
  for update;

  if not found then
    raise exception 'Booking not found.';
  end if;

  if v_booking.status = p_status then
    return;
  end if;

  select *
  into v_slot
  from public.availability_slots
  where service_type = v_booking.service_type
    and slot_date = v_booking.booking_date
    and slot_time = v_booking.booking_time
  for update;

  if p_status = 'cancelled' then
    if v_slot.id is not null then
      update public.availability_slots
      set is_booked = false
      where id = v_slot.id;
    end if;
  else
    if v_slot.id is null then
      raise exception 'The original availability slot no longer exists.';
    end if;

    if v_slot.is_booked then
      raise exception 'That slot has already been booked by someone else.';
    end if;

    update public.availability_slots
    set is_booked = true
    where id = v_slot.id;
  end if;

  update public.bookings
  set status = p_status
  where id = p_booking_id;
end;
$$;

revoke all on function public.set_booking_status(bigint, text) from public;
grant execute on function public.set_booking_status(bigint, text)
  to authenticated;

create or replace function public.save_project(
  p_project jsonb,
  p_images jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
  v_title text := trim(coalesce(p_project->>'title', ''));
  v_category text := trim(coalesce(p_project->>'category', ''));
begin
  if not public.is_admin() then
    raise exception 'Unauthorized.';
  end if;

  if v_title = '' or v_category = '' then
    raise exception 'Title and category are required.';
  end if;

  v_id := nullif(p_project->>'id', '')::bigint;

  if v_id is null then
    insert into public.projects (
      title, category, presentation_type, location, project_date,
      summary, goals, what_changed, client_items, purchased_items,
      constraints_text, service_format, featured, sort_order
    )
    values (
      v_title,
      v_category,
      coalesce(nullif(p_project->>'presentation_type', ''), 'before_after'),
      coalesce(p_project->>'location', ''),
      coalesce(p_project->>'project_date', ''),
      coalesce(p_project->>'summary', ''),
      coalesce(p_project->>'goals', ''),
      coalesce(p_project->>'what_changed', ''),
      coalesce(p_project->>'client_items', ''),
      coalesce(p_project->>'purchased_items', ''),
      coalesce(p_project->>'constraints_text', ''),
      coalesce(p_project->>'service_format', ''),
      coalesce((p_project->>'featured')::boolean, false),
      coalesce((p_project->>'sort_order')::integer, 0)
    )
    returning id into v_id;
  else
    if not exists (select 1 from public.projects where id = v_id) then
      raise exception 'Project not found.';
    end if;

    update public.projects
    set
      title = v_title,
      category = v_category,
      presentation_type = coalesce(nullif(p_project->>'presentation_type', ''), presentation_type),
      location = coalesce(p_project->>'location', ''),
      project_date = coalesce(p_project->>'project_date', ''),
      summary = coalesce(p_project->>'summary', ''),
      goals = coalesce(p_project->>'goals', ''),
      what_changed = coalesce(p_project->>'what_changed', ''),
      client_items = coalesce(p_project->>'client_items', ''),
      purchased_items = coalesce(p_project->>'purchased_items', ''),
      constraints_text = coalesce(p_project->>'constraints_text', ''),
      service_format = coalesce(p_project->>'service_format', ''),
      featured = coalesce((p_project->>'featured')::boolean, false),
      sort_order = coalesce((p_project->>'sort_order')::integer, 0)
    where id = v_id;
  end if;

  delete from public.project_images where project_id = v_id;

  insert into public.project_images (
    project_id, image_path, storage_path, label, sort_order
  )
  select
    v_id,
    image->>'image_path',
    nullif(image->>'storage_path', ''),
    coalesce(nullif(image->>'label', ''), 'gallery'),
    coalesce((image->>'sort_order')::integer, 0)
  from jsonb_array_elements(coalesce(p_images, '[]'::jsonb)) as image
  where coalesce(image->>'image_path', '') <> '';

  return v_id;
end;
$$;

revoke all on function public.save_project(jsonb, jsonb) from public;
grant execute on function public.save_project(jsonb, jsonb) to authenticated;

create or replace function public.delete_project(p_project_id bigint)
returns text[]
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_paths text[];
begin
  if not public.is_admin() then
    raise exception 'Unauthorized.';
  end if;

  select coalesce(
    array_agg(storage_path) filter (where storage_path is not null),
    array[]::text[]
  )
  into v_paths
  from public.project_images
  where project_id = p_project_id;

  delete from public.projects where id = p_project_id;

  return v_paths;
end;
$$;

revoke all on function public.delete_project(bigint) from public;
grant execute on function public.delete_project(bigint) to authenticated;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.admin_users enable row level security;
alter table public.bookings enable row level security;
alter table public.availability_slots enable row level security;
alter table public.waitlist enable row level security;
alter table public.settings enable row level security;
alter table public.projects enable row level security;
alter table public.project_images enable row level security;
alter table public.testimonials enable row level security;

drop policy if exists "Admin can view own admin record" on public.admin_users;
create policy "Admin can view own admin record"
on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "Admins can view bookings" on public.bookings;
create policy "Admins can view bookings"
on public.bookings for select to authenticated
using (public.is_admin());

drop policy if exists "Public can view open availability" on public.availability_slots;
create policy "Public can view open availability"
on public.availability_slots for select to anon, authenticated
using (is_booked = false or public.is_admin());

drop policy if exists "Admins can insert availability" on public.availability_slots;
create policy "Admins can insert availability"
on public.availability_slots for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update availability" on public.availability_slots;
create policy "Admins can update availability"
on public.availability_slots for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete open availability" on public.availability_slots;
create policy "Admins can delete open availability"
on public.availability_slots for delete to authenticated
using (public.is_admin() and is_booked = false);

drop policy if exists "Admins can view waitlist" on public.waitlist;
create policy "Admins can view waitlist"
on public.waitlist for select to authenticated
using (public.is_admin());

drop policy if exists "Admins can delete waitlist" on public.waitlist;
create policy "Admins can delete waitlist"
on public.waitlist for delete to authenticated
using (public.is_admin());

drop policy if exists "Public can read settings" on public.settings;
create policy "Public can read settings"
on public.settings for select to anon, authenticated
using (true);

drop policy if exists "Admins can insert settings" on public.settings;
create policy "Admins can insert settings"
on public.settings for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update settings" on public.settings;
create policy "Admins can update settings"
on public.settings for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete settings" on public.settings;
create policy "Admins can delete settings"
on public.settings for delete to authenticated
using (public.is_admin());

drop policy if exists "Public can read projects" on public.projects;
create policy "Public can read projects"
on public.projects for select to anon, authenticated
using (true);

drop policy if exists "Admins can insert projects" on public.projects;
create policy "Admins can insert projects"
on public.projects for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update projects" on public.projects;
create policy "Admins can update projects"
on public.projects for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete projects" on public.projects;
create policy "Admins can delete projects"
on public.projects for delete to authenticated
using (public.is_admin());

drop policy if exists "Public can read project images" on public.project_images;
create policy "Public can read project images"
on public.project_images for select to anon, authenticated
using (true);

drop policy if exists "Admins can insert project images" on public.project_images;
create policy "Admins can insert project images"
on public.project_images for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update project images" on public.project_images;
create policy "Admins can update project images"
on public.project_images for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete project images" on public.project_images;
create policy "Admins can delete project images"
on public.project_images for delete to authenticated
using (public.is_admin());

drop policy if exists "Public can read active testimonials" on public.testimonials;
create policy "Public can read active testimonials"
on public.testimonials for select to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists "Admins can insert testimonials" on public.testimonials;
create policy "Admins can insert testimonials"
on public.testimonials for insert to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update testimonials" on public.testimonials;
create policy "Admins can update testimonials"
on public.testimonials for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete testimonials" on public.testimonials;
create policy "Admins can delete testimonials"
on public.testimonials for delete to authenticated
using (public.is_admin());

-- ---------------------------------------------------------------------------
-- Data API privileges
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated;

grant select on public.availability_slots, public.settings,
  public.projects, public.project_images, public.testimonials
to anon, authenticated;

grant select on public.admin_users, public.bookings, public.waitlist
to authenticated;

grant insert, update, delete on public.availability_slots,
  public.settings, public.projects, public.project_images,
  public.testimonials
to authenticated;

grant delete on public.waitlist to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Storage bucket and policies
-- ---------------------------------------------------------------------------

insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
values (
  'project-images',
  'project-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can view project storage" on storage.objects;
create policy "Admins can view project storage"
on storage.objects for select to authenticated
using (bucket_id = 'project-images' and public.is_admin());

drop policy if exists "Admins can upload project images" on storage.objects;
create policy "Admins can upload project images"
on storage.objects for insert to authenticated
with check (bucket_id = 'project-images' and public.is_admin());

drop policy if exists "Admins can update project images in storage" on storage.objects;
create policy "Admins can update project images in storage"
on storage.objects for update to authenticated
using (bucket_id = 'project-images' and public.is_admin())
with check (bucket_id = 'project-images' and public.is_admin());

drop policy if exists "Admins can delete project images from storage" on storage.objects;
create policy "Admins can delete project images from storage"
on storage.objects for delete to authenticated
using (bucket_id = 'project-images' and public.is_admin());

-- ---------------------------------------------------------------------------
-- Defaults and initial virtual availability
-- ---------------------------------------------------------------------------

insert into public.settings (key, value) values
  ('in_person_status', 'fully_booked'),
  ('in_person_until', (current_date + 60)::text),
  ('in_person_message', 'Kura Space is currently fully booked for in-person organizing services.')
on conflict (key) do nothing;

insert into public.availability_slots (
  service_type, slot_date, slot_time, is_booked
)
select
  'virtual',
  day::date,
  slot_time::time,
  false
from generate_series(
  current_date + 1,
  current_date + 60,
  interval '1 day'
) as day
cross join (
  values ('09:00'), ('10:30'), ('12:00'), ('13:30'), ('15:00')
) as times(slot_time)
where extract(isodow from day) between 1 and 5
on conflict (service_type, slot_date, slot_time) do nothing;

commit;

-- AFTER creating your admin user in Authentication → Users, run:
-- insert into public.admin_users (user_id)
-- values ('PASTE-THE-AUTH-USER-UUID-HERE')
-- on conflict (user_id) do nothing;
